# This is the messages file for the Core plugin
# Almost every single message will be customizable here!

# Sent when the executer isn't a player
must-be-player: '&cYou must be a player to execute this command!'

# Sent when player is not online
player-not-online: '&cThis player is not online!'

# Sent when a player is not found
player-not-found: '&cPlayer not found!'

# Message sent when a player doesn't have permission to execute
# a Command
no-permission: '&cYou do not have permission to execute this command!'

# Option for changing Fly toggle messages
fly-true: '&eFly has been set to &aTrue'
fly-false: '&eFly has been set to &cFalse'

# Option for changing Gamemode messages
gamemode-creative: '&eGamemode has been set to &aCreative'
gamemode-survival: '&eGamemode has been set to &aSurvival'
gamemode-spectator: '&eGamemode has been set to &aSpectator'
gamemode-adventure: '&eGamemode has been set to &aAdventure'

# /msg Format
msg-format: '&e/msg &7(Player) (Message)'
# /r Format
reply-format: '&e/r &7(Message)'
# Message sent to messager when replying but no conversation has taken place
no-conversation: '&cNo conversation has taken place!'

# Sent when sender executes /discord
discord-output: '&bDiscord &7: &bhttps://discord.gg/invite-code-here'
# Sent when sender executes /website
website-output: '&aWebsite &7: &ahttps://your-link-here'

# /broascast Format
broadcast-format: '&c/(Broadcast, Alert, Announce) (message)'
# Broadcast prefix
broadcast-prefix: '&c&lALERT&7:&f '

# /kill Format
kill-format: '&e/kill &7(Player)'
# Sent to target when killed
player-killed-you: '&eYou have been &cKilled &eby &b'
# Sent to the sender when they kill someone else
killed-others: '&eYou have &cKilled &b'

# Sent when a player kills themself via /suicide
suicide-message: '&eYou have &cKilled &eyourself!'

# Sent when the target has been healed
target-healed: '&eYou have been &aHealed &eby &a'
# Sent to Sender when target has been healed
healed-others: '&eYou have &aHealed '
# Sent when you heal yourself
healed-self: '&eYou have &aHealed &eyourself!'

# Sent to target when they are fed
target-fed: '&eYou have been &aFed &eby &a'
# Sent to sender when they fed someone else
fed-others: '&eYou have &aFed '
# Sent to player who feed themself
fed-self: '&eYou have &aFed &eyourself!'

