name: Core
version: ${project.version}
main: me.fazzyplayzmc.core.Core
api-version: 1.16
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
authors: [ FazzyPlayzMc ]
description: Core plugin
website: []
commands:
  fly:
    description: Toggle Fly
    usage: /<command>
  gmc:
    description: Toggle gamemode creative
    usage: /<command>
  gms:
    description: Toggle gamemode survival
    usage: /<command>
  gmsp:
    description: Toggle gamemode spectator
    usage: /<command>
  gma:
    description: Toggle gamemode adventure
    usage: /<command>


