name: Core
version: ${project.version}
main: me.fazzyplayzmc.core.Core
api-version: 1.16
depend: [ Vault ]
softdepend: []
authors: [ FazzyPlayzMc ]
description: Core plugin
website: []
commands:
  fly:
    description: Toggle Fly
  fspeed:
    description: Set flying speed
  wspeed:
    description: Set walking speed
  gmc:
    description: Toggle gamemode creative
  gms:
    description: Toggle gamemode survival
  gmsp:
    description: Toggle gamemode spectator
  gma:
    description: Toggle gamemode adventure
  msg:
    description: Message other players
  r:
    description: Reply to player messages
  discord:
    description: Display discord server invite link
  website:
    description: Display website link
    aliases: [web]
  broadcast:
    description: Send an announcement to everyone
    aliases: [announce, alert]
  kill:
    description: Kill a player
  suicide:
    description: Kill yourself
  heal:
    description: Heal yourself or another player
  feed:
    description: Feed yourself or another player
  smite:
    description: Smite a player (lmao)
    aliases: [lightning]
  burn:
    description: Set player on fire
    aliases: [fire]
  clearinventory:
    description: Clear yours or other players Inventory
    aliases: [ci, clear, clearinv]
  tp:
    description: Teleport to players
    aliases: [teleport]
  tphere:
    description: Teleport players to you
  tpall:
    description: Teleport every player to your location
  god:
    description: Become invincible or turn someone else invincible
  nick:
    description: Change your display name
  repair:
    description: Repair items in your hand
  spawn:
    description: Teleport to spawn set in config






